name = "lsda-hubbard"
version = "0.1.0"
license = "MIT"
author = "Guilherme Canella"
maintainer = "guycanella@gmail.com"
copyright = "2025 Guilherme Canella"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[dependencies]

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "test_bethe_equations"
source-dir = "test"
main = "test_bethe_equations.f90"

[[executable]]
name = "lsdaks"
source-dir = "app"
main = "main.f90"

[dev-dependencies]
fortuno = { git = "https://github.com/fortuno-repos/fortuno-fpm-serial.git" }
