name = "lsda-hubbard"
version = "0.1.0"
license = "MIT"
author = "Guilherme Canella"
maintainer = "guycanella@gmail.com"
copyright = "2025 Guilherme Canella"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["lapack", "blas"]

[[executable]]
name = "convert_tables"
source-dir = "app"
main = "convert_tables.f90"

[dependencies]

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "test_bethe_equations"
source-dir = "test"
main = "test_bethe_equations.f90"

[[test]]
name = "test_nonlinear_solvers"
source-dir = "test"
main = "test_nonlinear_solvers.f90"

[[test]]
name = "test_continuation"
source-dir = "test"
main = "test_continuation.f90"

[[test]]
name = "test_table_io"
source-dir = "test"
main = "test_table_io.f90"

[[test]]
name = "test_bethe_tables"
source-dir = "test"
main = "test_bethe_tables.f90"

[[test]]
name = "test_density_calculator"
source-dir = "test"
main = "test_density_calculator.f90"

[[test]]
name = "test_convergence_monitor"
source-dir = "test"
main = "test_convergence_monitor.f90"

[[test]]
name = "test_mixing_schemes"
source-dir = "test"
main = "test_mixing_schemes.f90"

[[executable]]
name = "lsdaks"
source-dir = "app"
main = "main.f90"

[dev-dependencies]
fortuno = { git = "https://github.com/fortuno-repos/fortuno-fpm-serial.git" }
